import "./App.css";
import { useState } from "react";
import FileUpload from "./components/FileUpload.jsx";
import FileUploadDecode from "./components/FileUploadDecode.jsx";
import HuffmanTreeVisualizer from "./components/HuffmanTreeVisualizer.jsx";
import HuffmanTreeAnimation from "./components/HuffmanTreeAnimation.jsx";
import { demoData } from "./utils/DemoTree.js";
import MainContent from "./components/MainContent.jsx";
import References from "./components/References.jsx";
import Heading from "./components/Heading.jsx";

function App() {
  const [treeData, setTreeData] = useState(null);

  const handleFileUpload = (data) => {
    setTreeData(data);
  };

  return (
    <div className="relative h-full w-full bg-slate-950 overflow-hidden">
      <div className="absolute bottom-0 left-[-20%] right-0 top-[-10%] h-[500px] w-[500px] rounded-full bg-[radial-gradient(circle_farthest-side,rgba(255,0,182,.15),rgba(255,255,255,0))]"></div>
      <div className="absolute bottom-0 right-[-10%] top-[10%] h-[500px] w-[500px] rounded-full bg-[radial-gradient(circle_farthest-side,rgba(255,0,182,.20),rgba(255,255,255,0))]"></div>
      <div className="absolute bottom-0 left-[-10%] right-0 top-[40%] h-[500px] w-[500px] rounded-full bg-[radial-gradient(circle_farthest-side,rgba(255,0,182,.15),rgba(255,255,255,0))]"></div>
      <div className="absolute bottom-0 right-[-10%] top-[60%] h-[500px] w-[500px] rounded-full bg-[radial-gradient(circle_farthest-side,rgba(255,0,182,.15),rgba(255,255,255,0))]"></div>
      {/* Main  */}
      <div>
        <Heading />
        <div className="flex justify-evenly">
          <FileUpload onUpload={handleFileUpload} />
          <div className=" min-h-full border-[1px] border-white opacity-10"></div>
          <FileUploadDecode onUpload={handleFileUpload} />
        </div>
        <div className="m-5 flex justify-center text-white w-full">
          <p className="py-2 px-10 text-center bg-red-400 rounded-xl">
            ⚠️ Above implementation only works for text files with .txt format
            and compressed files generated by this which are in .bin format
          </p>
        </div>
        {treeData && <HuffmanTreeVisualizer treeData={treeData} />}
        <MainContent />
        <div>
          <HuffmanTreeAnimation data={demoData} />
        </div>
      </div>
      <div>
        <References />
      </div>
    </div>
  );
}

export default App;
